openapi: 3.0.3
info:
  title: CofeGB
  description: CofeGB app rest api specification
  version: 1.0.0
tags:
  - name: menu
    description: app navigation menu entries
  - name: category
    description: Dish menu entries
paths:
  /navMenu:
    get:
      tags:
        - menu
      description: Return app navigation menu entries
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/navMenuItem'
  /categories:
    get:
      tags:
        - category
      description: Returns dish menu entries
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/category'
components:
  schemas:
    navMenuItem:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 1
        title:
          type: string
          example: Закуски
        route:
          type: string
          example: /menu
        icon:
          type: string
          example: starters
        query:
          type: string
          example: starters
        warn:
          type: boolean
          example: false
        warnMsg:
          type: string
    category:
      type: object
      properties:
        guid:
          type: string
          example: 94b1f98d-13e3-4d58-a9b7-86b734daf77d
        title:
          type: string
          example: Закуски
        icon:
          type: string
          example: starters
        query:
          type: string
          example: starters
