openapi: 3.0.3
info:
  title: CofeGB
  description: CofeGB app rest api specification
  version: 1.0.0
tags:
  - name: nawmenu
    description: app navigation menu entries
  - name: category
    description: Dish menu entries
paths:
  /api/navMenu:
    get:
      tags:
        - nawmenu
      description: Return app navigation menu entries
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/navMenuItem'
  /categories:
    get:
      tags:
        - category
      description: Returns dish menu entries
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/category'
components:
  schemas:
    navMenuItem:
      type: object
      properties:
        title:
          type: string
          example: Закуски
        patch:
          type: string
          example: /menu/startes
        itemOrder:
          type: integer
          example: 0
        
    category:
      type: object
      properties:
        guid:
          type: string
          example: 94b1f98d-13e3-4d58-a9b7-86b734daf77d
        title:
          type: string
          example: Закуски
        icon:
          type: string
          example: starters
        query:
          type: string
          example: starters
